# Generated by Django 4.1.5 on 2023-01-27 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True, verbose_name='символ кнопки')),
            ],
            options={
                'verbose_name': 'кнопка',
                'verbose_name_plural': 'кнопки',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.button', verbose_name='кнопка')),
            ],
            options={
                'verbose_name': 'клавиатура',
                'verbose_name_plural': 'клавиатуры',
                'ordering': ('-id',),
            },
        ),
    ]
