# Generated by Django 4.1.5 on 2023-01-27 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyboard',
            name='button',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.button', unique=True, verbose_name='кнопка'),
        ),
    ]
